version: "3"

services:
    server:
        build: ./
        command: python -m server
        ports:
            - 9999:9999
        depends_on:
            - db
    db:
        image: postgres
        environment:
            POSTGRES_PASSWORD: 123456789test_user
